### ISSUE TITLE
Crash when unplugging USB cable (v0.9rc4, Mac)

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#194]
While knitting, unplugging the USB cable causes the application (but not the AYAB-titled python "terminal" window) to crash.

Able to reproduce several times, at different stages of knitting. 

To capture a traceback, I unplugged it before moving the carriage. Clicked "Knit", got this message:

```
Notification: Please init machine. (Set the carriage to mode KC-I or KC-II and move the carriage over the left turn mark).
```

(Everything OK up to here.) After receiving this message, I unplugged the USB cable and crashed the program:

```
Traceback (most recent call last):
  File "/Users/oskay/Downloads/AYAB.app/Contents/Resources/ayab/ayab.py", line 565, in run
    self.function(*self.args, **self.kwargs)
  File "/Users/oskay/.pyenv/versions/3.5.0/Python.framework/Versions/3.5/lib/python3.5/site-packages/fysom/__init__.py", line 300, in fn
    self.transition()
  File "/Users/oskay/.pyenv/versions/3.5.0/Python.framework/Versions/3.5/lib/python3.5/site-packages/fysom/__init__.py", line 295, in _tran
    self._after_event(e)
  File "/Users/oskay/.pyenv/versions/3.5.0/Python.framework/Versions/3.5/lib/python3.5/site-packages/fysom/__init__.py", line 326, in _after_event
    return getattr(self, fnname)(e)
  File "/Users/oskay/.pyenv/versions/3.5.0/Python.framework/Versions/3.5/lib/python3.5/site-packages/fysom/__init__.py", line 89, in _callback
    return func(obj, *args, **kwargs)
  File "/Users/oskay/Downloads/AYAB.app/Contents/Resources/ayab/plugins/ayab_plugin/ayab_control.py", line 37, in onknit
    self.__knitImage(self.__image, self.conf)
  File "/Users/oskay/Downloads/AYAB.app/Contents/Resources/ayab/plugins/ayab_plugin/ayab_control.py", line 604, in __knitImage
    rcvMsg, rcvParam = self.__checkSerial()
  File "/Users/oskay/Downloads/AYAB.app/Contents/Resources/ayab/plugins/ayab_plugin/ayab_control.py", line 334, in __checkSerial
    line = self.__ayabCom.read_line()
  File "/Users/oskay/Downloads/AYAB.app/Contents/Resources/ayab/plugins/ayab_plugin/ayab_communication.py", line 73, in read_line
    while self.__ser.inWaiting() > 0:
  File "/Users/oskay/.pyenv/versions/3.5.0/Python.framework/Versions/3.5/lib/python3.5/site-packages/serial/serialutil.py", line 588, in inWaiting
    return self.in_waiting
  File "/Users/oskay/.pyenv/versions/3.5.0/Python.framework/Versions/3.5/lib/python3.5/site-packages/serial/serialposix.py", line 467, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
OSError: [Errno 6] Device not configured
/Users/oskay/Downloads/AYAB.app/Contents/Resources/script: line 41:  1083 Abort trap: 6           /Users/$USER/.pyenv/shims/python3 ayab_devel_launch.py
```

No crash occurs if the knitting is cancelled before unplugging the USB cable.

**Comment by derchrisuk** [comment]
Is this still happening with the latest version?

**Comment by Adrienne200** [comment]
Yes. I downloaded RC4-Mac yesterday (June 19th) after you posted. This still happens.
Although logged against Mac, it happens on Windows too.

**Comment by chris007de** [comment]
I propose to shift this into the next milestone, as this is more a user/usability issue than a bug.

**Comment by Adrienne200** [comment]
Agreed.

**Comment by Adrienne200** [comment]
This crash hasn't been happening in 1.0 for a while. Retested with Beta3 on an Intel Mac.
