### ISSUE TITLE
Import error when running AYAB on Ubuntu

### ISSUE THREAD

**Issue by amydouang** [AllYarnsAreBeautiful/ayab-desktop#266]
when I try to run ayab I keep getting an import error.

phan@phan-Laptop:~$ ayab
Traceback (most recent call last):
  File "/home/phan/.local/bin/ayab", line 6, in <module>
    ayab.run()
  File "/home/phan/src/ayab/ayab/__init__.py", line 3, in run
    from .ayab import run
  File "/home/phan/src/ayab/ayab/ayab.py", line 26, in <module>
    from PyQt5 import QtWidgets, QtGui, QtCore
ImportError: /home/phan/.local/lib/python3.5/site-packages/PyQt5/QtCore.so: undefined symbol: PySlice_AdjustIndices

**Comment by chris007de** [comment]
Please describe the steps you performed to install AYAB

**Comment by chris007de** [comment]
@amydouang thanks for your patience.
Could you please try again, following these instructions:
https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/264#issuecomment-396335325

**Comment by amydouang** [comment]
I tried, but the same thing is still happening.

**Comment by chris007de** [comment]
@boisophieron Please post the console output when you try to run the software, otherwise we have no idea what is happening and how to fix it.

**Comment by derchrisuk** [comment]
@amydouang what python version you are using?

**Comment by amydouang** [comment]
@derchrisuk I am using python 3.

**Comment by derchrisuk** [comment]
@amydouang what exact version ...

**Comment by chris007de** [comment]
No activity for a long time -> closing.
