### ISSUE TITLE
state of development of v1

### ISSUE THREAD

**Issue by omeliailiffe** [AllYarnsAreBeautiful/ayab-desktop#437]
Kia ora
I have finally found some time to do some development work on ayab but have been struggling to get anything working.
I have built the firmware from v1.0-dev branch of ayab-firmware and have a dev environment for 1.0.0-dev ayab desktop
but when i attempt to knit I encounter crashes on the desktop due to unhanded errors from the firmware.

any pointers on getting a development version working so I can help out would be appreciated :)

**Comment by chris007de** [comment]
Hi, glad to hear that you want to contribute!
Could you please supply some information on your setup (operating system, python version) and the steps you performed to get the software running (installed dependencies) and most importantly, the output of the logfile with the errors you encounter.

Thanks a lot!

**Comment by omeliailiffe** [comment]
Thank you for your reply. 
I wrote that at the end of a frustrating day and didn't think to include all the helpful things.

I am using Ubuntu 20.04.4 LTS
Python is setup using Conda as described in the readme using Python 3.6.15
```
    pip3 install --upgrade pip
    pip3 install --upgrade setuptools
    python3 -m pip install -r requirements.txt
    ./setup-environment.sh
```

I have flashed ayab-firmware from branch v1.0-dev onto a known working board+machine.
building it with ```./build.sh``` and flashing the resulting ```ayab_monolithic_uno.hex```

I run ayab-desktop with ```python3 -m fbs run``` and setup a singlebed 2 color knit with the included mushroom sample.
After clicking configure and knit, I can see errors in the terminal

Ayab desktop is not handling a msg from the firmware ```0xe0``` which appears to be defined here as [testRes_msgid](https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/a5ab18641c5d346a82fca19fc31524ba678f66e9/src/ayab/com.h#L64) and here as [MACHINE_STATE_INIT](https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/a5ab18641c5d346a82fca19fc31524ba678f66e9/src/ayab/com.h#L98)

I can't quite wrap my head around it. Looking forward to hearing from you and excited to contribute more!

```
2022-06-27 10:24:15,493 root     DEBUG    Entered state CONFIGURING
2022-06-27 10:24:30,452 root     DEBUG    Entered state CHECKING
2022-06-27 10:24:30,453 Engine   DEBUG    {'portname': '/dev/ttyUSB1', 'machine': 'KH910_KH950', 'mode': 'SINGLEBED', 'num_colors': 2, 'start_row': 0, 'inf_repeat': False, 'start_needle': 82, 'stop_needle': 117, 'alignment': 'CENTER', 'auto_mirror': False, 'continuous_reporting': False}
2022-06-27 10:24:30,483 root     DEBUG    Entered state KNITTING
2022-06-27 10:24:30,483 Control  DEBUG    State SETUP
2022-06-27 10:24:30,483 Control  DEBUG    Port name: /dev/ttyUSB1
2022-06-27 10:24:30,485 Control  DEBUG    State INIT
2022-06-27 10:24:30,586 Control  DEBUG    State INIT
2022-06-27 10:24:30,687 Control  DEBUG    State INIT
2022-06-27 10:24:30,788 Control  DEBUG    State INIT
2022-06-27 10:24:30,890 Control  DEBUG    State INIT
2022-06-27 10:24:30,991 Control  DEBUG    State INIT
2022-06-27 10:24:31,092 Control  DEBUG    State INIT
2022-06-27 10:24:31,193 Communication DEBUG    unknown message: 
Operation.KNIT
Traceback (most recent call last):
  File "/home/fablab/ayab-desktop/src/main/python/ayab/thread.py", line 37, in run
    self.function(*self.args, **self.kwargs)
  File "/home/fablab/ayab-desktop/src/main/python/ayab/engine/engine.py", line 168, in run
    output = self.control.operate(operation)
  File "/home/fablab/ayab-desktop/src/main/python/ayab/engine/control.py", line 225, in operate
    result = dispatch(self, operation)
  File "/home/fablab/ayab-desktop/src/main/python/ayab/engine/state.py", line 111, in _API6_init
    token, param = control.check_serial_API6()
  File "/home/fablab/ayab-desktop/src/main/python/ayab/engine/control.py", line 119, in check_serial_API6
    msg, token, param = self.com.update_API6()
  File "/home/fablab/ayab-desktop/src/main/python/ayab/engine/communication.py", line 160, in update_API6
    return self.parse_API6(self.read_API6())
  File "/home/fablab/ayab-desktop/src/main/python/ayab/engine/communication.py", line 172, in parse_API6
    pp.pprint(msg.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 0: invalid continuation byte
2022-06-27 10:24:31,194 root     DEBUG    Entered state CONFIGURING
```

**Comment by omeliailiffe** [comment]
Whoops I was 2 commits behind.
Now the errors are able to decode.

It looks like the machine is in a testing state and will not knit. Unsure of what to try next.

```
2022-06-27 10:44:58,688 Control  INFO     API v6, FW v1.0
2022-06-27 10:44:58,689 Control  DEBUG    State REQUEST_START
2022-06-27 10:44:58,790 Communication DEBUG    unknown message: 
'Called readEncoders'
2022-06-27 10:44:58,791 Control  DEBUG    State REQUEST_START
2022-06-27 10:44:58,892 Communication DEBUG    unknown message: 
'  ENC_A:'
2022-06-27 10:44:58,893 Control  DEBUG    State REQUEST_START
2022-06-27 10:44:58,994 Communication DEBUG    unknown message: 
'HIG'
2022-06-27 10:44:58,995 Control  DEBUG    State REQUEST_START
2022-06-27 10:44:59,095 Communication DEBUG    unknown message: 
'  ENC_B:'
2022-06-27 10:44:59,096 Control  DEBUG    State REQUEST_START
2022-06-27 10:44:59,197 Communication DEBUG    unknown message: 
'LO'
2022-06-27 10:44:59,198 Control  DEBUG    State REQUEST_START
2022-06-27 10:44:59,299 Communication DEBUG    unknown message: 
'  ENC_C:'
2022-06-27 10:44:59,300 Control  DEBUG    State REQUEST_START
2022-06-27 10:44:59,401 Communication DEBUG    unknown message: 
'HIG'
2022-06-27 10:44:59,401 Control  DEBUG    State REQUEST_START
2022-06-27 10:44:59,502 Communication DEBUG    unknown message: 
''

```

**Comment by chris007de** [comment]
Hi @omeliailiffe, sorry for letting you wait for my reply!

Hm..that's a bit strange...the Serial Output you are receiving ('Called readEncoders', '  ENC_A:', ...) let's me assume that there is a pretty old version of the HW_TEST firmware running on the Arduino. (see https://github.com/AllYarnsAreBeautiful/ayab-firmware/search?q=ENC_A%3A for instance).
Such an output is not included on the code on the dev-1.0 as far as I can see...
Could you please double check that flashing the firmware you built was successful?

Best Regards

**Comment by omeliailiffe** [comment]
No worries at all.
I’m on holiday away from my setup so I can’t double check that the firmware was successfully flashed however I was able to find the `ENC_A` in the [tester.cpp file on the dev-1.0 branch](https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/a5ab18641c5d346a82fca19fc31524ba678f66e9/src/ayab/tester.cpp#L236). Unsure why this doesn’t show in the search.

I have to be honest. I find the dev-1.0 branch quite hard to read when compared to 0.95, so it’s tricky for me to figure out why or when this code is being called.

**Comment by chris007de** [comment]
Seems that the firmware somehow interprets the command from the software as `readEncodersCmd_msgid`...which should not be sent in the state `REQUEST_START`.
I have to admit I have to set up a dev environment first to be able to track this down... in the meantime, any hints from @t0mpr1c3 or @Sturla22 about this?

Let's see if we can get this working!

**Comment by dl1com** [comment]
This issue seems to be obsolete, closing for now
