### ISSUE TITLE
Starting to knit in simulation mode fails

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#469]
Build: test230514
Installed via: source

After choosing port "Simulation" and trying to "Knit" with the default settings, nothing happens in the UI.
Log output shows:

```
2023-05-14 12:59:09,517 root     DEBUG    Entered state CONFIGURING
2023-05-14 12:59:50,378 root     DEBUG    Entered state CHECKING
2023-05-14 12:59:50,379 Engine   DEBUG    {'portname': 'Simulation', 'machine': 'KH910_KH950', 'mode': 'SINGLEBED', 'num_colors': 2, 'start_row': 0, 'inf_repeat': False, 'start_needle': 85, 'stop_needle': 114, 'alignment': 'CENTER', 'auto_mirror': False, 'continuous_reporting': False}
2023-05-14 12:59:50,385 root     DEBUG    Entered state KNITTING
2023-05-14 12:59:50,385 Control  DEBUG    State CONNECT
2023-05-14 12:59:50,386 Control  DEBUG    Port name: Simulation
2023-05-14 12:59:50,386 Control  DEBUG    State VERSION_CHECK
2023-05-14 12:59:50,386 Control  DEBUG    State VERSION_CHECK
2023-05-14 12:59:50,387 Control  INFO     API v6, FW v1.0
2023-05-14 12:59:50,387 Control  DEBUG    State INIT
Carriage.Lace
Direction.Right
Operation.KNIT
Traceback (most recent call last):
  File "/home/chris/projects/github/allyarnsarebeautiful/ayab-desktop/src/main/python/ayab/thread.py", line 37, in run
    self.function(*self.args, **self.kwargs)
  File "/home/chris/projects/github/allyarnsarebeautiful/ayab-desktop/src/main/python/ayab/engine/engine.py", line 168, in run
    output = self.control.operate(operation)
  File "/home/chris/projects/github/allyarnsarebeautiful/ayab-desktop/src/main/python/ayab/engine/control.py", line 225, in operate
    result = dispatch(self, operation)
  File "/home/chris/projects/github/allyarnsarebeautiful/ayab-desktop/src/main/python/ayab/engine/state.py", line 144, in _API6_init
    control.com.req_init_API6(control.machine.value)
  File "/home/chris/projects/github/allyarnsarebeautiful/ayab-desktop/src/main/python/ayab/engine/communication.py", line 143, in req_init_API6
    data = self.__driver.send(bytes(data))
AttributeError: 'CommunicationMock' object has no attribute '_Communication__driver'
2023-05-14 12:59:50,389 root     INFO     Notification: Please start machine. (Set the carriage to mode KC-I or KC-II and move the carriage over the left turn mark).
2023-05-14 12:59:50,390 root     DEBUG    Entered state CONFIGURING
```

**Comment by dl1com** [comment]
Tested in https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/test230515 on Windows 10, still showing the same error.

**Comment by t0mpr1c3** [comment]
In [test230518](https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/test230518), it spews START_REQUEST ad infinitum.
