### ISSUE TITLE
[BUG] AYAB Appimage does not launch

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#609]
**Environment**
AYAB software version: 0.99.0-rc2
Computer/OS: Debian Bullseye
Knitting machine: --
AYAB hardware: --

**Describe the bug**
Ayab Appimage does not launch throws the following error:

```
Traceback (most recent call last):
  File "/tmp/.mount_AYAB-0pLIeHm/src/main/python/main.py", line 13, in <module>
    from ayab.ayab import GuiMain
  File "/tmp/.mount_AYAB-0pLIeHm/src/main/python/ayab/ayab.py", line 31, in <module>
    from .signal_receiver import SignalReceiver
  File "/tmp/.mount_AYAB-0pLIeHm/src/main/python/ayab/signal_receiver.py", line 22, in <module>
    from .engine.status import Status
  File "/tmp/.mount_AYAB-0pLIeHm/src/main/python/ayab/engine/__init__.py", line 1, in <module>
    from . import engine
  File "/tmp/.mount_AYAB-0pLIeHm/src/main/python/ayab/engine/engine.py", line 30, in <module>
    from .control import Control
  File "/tmp/.mount_AYAB-0pLIeHm/src/main/python/ayab/engine/control.py", line 29, in <module>
    from .options import Alignment
  File "/tmp/.mount_AYAB-0pLIeHm/src/main/python/ayab/engine/options.py", line 28, in <module>
    from .options_gui import Ui_Options
  File "/tmp/.mount_AYAB-0pLIeHm/src/main/python/ayab/engine/options_gui.py", line 145, in <module>
    import ayab.engine.lowercase_e_reversed_rc
ModuleNotFoundError: No module named 'ayab.engine.lowercase_e_reversed_rc'
```

Seems to be related to #608, as the lowercase e was added in this PR afaik.

**To Reproduce**
Download Appimage from Release page and run

**Comment by X-sam** [comment]
#635 supercede
